--UPDATE CONTACTS TABLE
ALTER TABLE {{schema_name}}.contacts
DROP COLUMN IF EXISTS first_name,
DROP COLUMN IF EXISTS middle_name,
DROP COLUMN IF EXISTS last_name,
DROP COLUMN IF EXISTS phone,
DROP COLUMN IF EXISTS address,
DROP COLUMN IF EXISTS tags,
DROP COLUMN IF EXISTS email;

ALTER TABLE {{schema_name}}.contacts
ADD COLUMN IF NOT EXISTS name TEXT,
ADD COLUMN IF NOT EXISTS phone JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS address JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS email JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS tags TEXT[],
ADD COLUMN IF NOT EXISTS archived BOOLEAN DEFAULT FALSE;