--CREATE CONTACTS TABLE
CREATE TABLE IF NOT EXISTS public.contacts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    first_name TEXT NOT NULL,
    middle_name TEXT,
    last_name TEXT,
    abbreviation_name TEXT,
    full_name TEXT NOT NULL,
    prefix TEXT,
    suffix TEXT,
    fullname_extended TEXT,
    is_individual BOOLEAN NOT NULL DEFAULT FALSE,
    is_deceased BOOLEAN DEFAULT FALSE,
    death_date DATE,
    birth_date DATE,
    age_in_years INTEGER,
    last_changed TIMESTAMP,
    is_archived BOOLEAN NOT NULL DEFAULT FALSE,
    is_protected BOOLEAN NOT NULL DEFAULT FALSE,
    score INTEGER,
    addresses JSONB DEFAULT '[]'::jsonb,
    emails JSONB DEFAULT '[]'::jsonb,
    phones JSONB DEFAULT '[]'::jsonb,
    contact_type_ids UUID[],
    tags_v2 TEXT[],
    hashtags TEXT[],
    flattened_hash_tags TEXT,
    group_by_first TEXT,
    sort_by_first TEXT,
    group_by_last TEXT,
    sort_by_last TEXT,
    picture_url TEXT,
    company TEXT,
    department TEXT,
    job_title TEXT,
    org_id INTEGER,
    org_name TEXT,
    team_ids TEXT[],
    picture_key TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_contacts_name ON public.contacts(first_name);